#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/systemd/system/docker.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start Dynamic Docker image

    [Service]
    Restart=always
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/share/google/dockercfg_update.sh
    ExecStart=/usr/bin/docker run --name=%s \
                                  %s
    ExecStop=/usr/bin/docker stop %s

runcmd:
- systemctl daemon-reload
- systemctl start docker.service