#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/systemd/system/opencpu.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start OpenCPU with RStudio

    [Service]
    Restart=always
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/share/google/dockercfg_update.sh
    ExecStart=/usr/bin/docker run -p 80:80 \
                                  -p 8004:8004 \
                                  --name=opencpu-server \
                                  %s
    ExecStop=/usr/bin/docker stop opencpu
    ExecStopPost=/usr/bin/docker rm opencpu

runcmd:
- systemctl daemon-reload
- systemctl start opencpu.service